live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Hack Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 1

[mouse]
hide_when_typing = false

[scrolling]
history = 5000

[selection]
save_to_clipboard = false

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
